language: rust
cache: cargo

matrix:
  include:
    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin OPENSSL_STATIC=yes
      script: cargo build --release --target $TARGET --features=all
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl OPENSSL_DIR=$HOME/openssl-musl
      before_script: ./scripts/travis-musl-openssl.sh
      script: cargo build --release --target $TARGET --features=all
      addons:
        apt:
          packages:
          - musl-tools
  allow_failures:
    - rust: nightly

before_script:
  - export EXTRA_FEATURES=
  - if [[ "${TRAVIS_RUST_VERSION}" = "nightly" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES unstable"; fi
  - if [[ "${DIST_SCCACHE}" = "1" ]]; then export EXTRA_FEATURES="$EXTRA_FEATURES dist-client dist-server"; fi

script:
  - cargo build --verbose --features="all ${EXTRA_FEATURES}"

before_deploy:
  - "./scripts/prep_deploy.sh"

deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz
    - sccache-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  on:
    condition: $DEPLOY = 1
    tags: true
  skip_cleanup: true
